### ISSUE TITLE
Drag & Drop for subtitles

### ISSUE THREAD

**Issue by mrcdnk** [mpvqc/mpvQC#1]
It would be cool, if this was a feature and I don't think this would be hard to add. (Most of the time the subtitle file does not have the same name as the video. because there is additional information contained like who edited or timed it)

**Comment by Frechdachs** [comment]
I could probably do that if I set the `sub-file` option during playback. I can look into that.

>because there is additional information contained like who edited or timed it

To fix this you can go to `Options --> Edit mpv.conf...` and add the following line:
```
sub-auto=fuzzy
```
Then if your video file is called `filename.mkv` it will not only load `filename.ass` but also for example `filename.herp.derp.ass`

**Comment by Asbestion** [comment]
I'll try that, thanks. We normally add these informations like this:  
`[SubGroup] filename [TL_Herp, Edit_Derp].ass`
I'm not familiar with mpv, but maybe its possible to set the `sub-file` before playback when the video is selected and expose something like a regex expression or function to compare the file names for customization.

**Comment by Frechdachs** [comment]
>[SubGroup] filename [TL_Herp, Edit_Derp].ass

This will work with `sub-auto=fuzzy`. And just for your information `sub-auto=all` will load every subtitle file that is in the directory of the video file.

>I'm not familiar with mpv, but maybe its possible to set the sub-file before playback when the video is selected and expose something like a regex expression or function to compare the file names for customization.

Well that's essentially what mpv does with `sub-auto=fuzzy`.

But adding support for drag and drop of subtitle files sounds like a good idea.

**Comment by Frechdachs** [comment]
>and expose something like a regex expression or function to compare the file names for customization.

>Well, that's essentially what mpv does with sub-auto=fuzzy.

Oh, you mean so that the user can enter his own regular expression in mpvQC? Not sure about that.

**Comment by Frechdachs** [comment]
Latest commit implements drag and drop for subtitle files. If a video file is already loaded then mpvQC will load and select the dropped subtitle file. Wether dropped file is a subtitle or not is determined by its extension.

I'll leave this issue open until I bother to make a new package for Windows.

**Comment by Frechdachs** [comment]
Finally made a new release. :)
