### ISSUE TITLE
Linux: Improve Rendering Performance

### ISSUE THREAD

**Issue by trin94** [mpvqc/mpvQC#26]
The rendering performance issue is caused by us rendering into the same framebuffer as Qt renders its UI. When playing 24 fps videos, this reduces the framerate being rendered to 24 fps. And therefore menu animations and GUI interactions result in a bad user experience.

We tried playing around with mpv not blocking for the next frame but that leads to frame drops mpvqc/mpvQC-dev#61.

We need to find a different way to improve performance. 

Ideas:
* Use two framebuffers (1x onscreen for Qt, 1x offscreen for mpv)

**Comment by trin94** [comment]
Maybe using something like this helps: https://doc-snapshots.qt.io/qt6-6.5/qtquick-itemvariablerefreshrate-example.html

**Comment by trin94** [comment]
Asked for help in the Qt forum: https://forum.qt.io/topic/149728/improve-rendering-performance-while-integrating-libmpv-with-qtquick-python

**Comment by barribarrier** [comment]
Hi @trin94 

I've tested this with 24fps and 5fps videos but the UI seems unaffected? I don't notice any lag or slowdowns when interacting with the UI.

Tested on linux.

**Comment by trin94** [comment]
This rendering issue only applies for Linux on both x11 and Wayland. On Windows, we now do hWnd embedding instead of libmpv rendering. Unless someone has a clever idea, I don't think we can do much about it until there's a Wayland protocol including common compositor support for this.

**Comment by trin94** [comment]
For Linux users, a temporary fix is to adjust the [video-timing-offset](https://mpv.io/manual/master/#options-video-timing-offset) setting in mpv (`Options` → `Edit mpv.conf...`):

By default, **video-timing-offset** is set to `0.050`. On a 120 Hz monitor, we want the video to match the refresh rate, which is 120 frames per second (fps). This means each frame should appear every `1000 / 120 ≈ 8.3 ms`. By lowering the **video-timing-offset** (e.g., to `0.008`), mpvQC will reduce the maximum frame delay from `50 ms` (default) to about `8 ms`, keeping video and monitor refresh rates in sync.

Here are suggested values for different frame rates:

| Target Frame Rate | Frame Time Calculation       | Recommended Offset         |
|-------------------|------------------------------|-----------------------------|
| `60` fps          | `1000 ms / 60 ≈ 16.6 ms`     | `video-timing-offset=0.016` |
| `120` fps         | `1000 ms / 120 ≈ 8.3 ms`     | `video-timing-offset=0.008` |
| `240` fps         | `1000 ms / 240 ≈ 4.2 ms`     | `video-timing-offset=0.004` |

**Note:** This requires powerful hardware, and even with adjustments, you might still see frame drops or audio sync issues. You can check for any audio-video drift in mpvQC by pressing `i` to display video stats. If you experience frame drops, consider lowering the target frame rate.

**Comment by trin94** [comment]
This issue will be closed with no changes. We'll monitor Wayland protocols and make adjustments if any updates occur.
