### ISSUE TITLE
Contribution to add Spanish language

### ISSUE THREAD

**Issue by RcUchiha** [mpvqc/mpvQC#8]
As the title says, I would like to know how I can add a new language to the tool.

I would like to do a personal build or even collaborate for an official one.

**Comment by trin94** [comment]
Hey @RcUchiha,

You'll need a few tools for the translation:
- Python 3.6+
- QtLinguist
- [distuitls_ui](https://github.com/frispete/distutils_ui)

1. Change directory to `i18n`
2. Create a new file `<abc>.ts`
3. In the main directory of this project run `python3 setup.py build_ui`
4. Open `i18n/<abc>.ts` with QtLinguist and translate
5. In the main directory of this project run `python3 setup.py build_ui` to update binaries
6. Submit pull request

**Note**: New languages are not available in the GUI immediately.

Taken from: https://github.com/mpvqc/mpvQC/blob/master/DEVELOPMENT.MD

Regards,
Elias

**Comment by RcUchiha** [comment]
Well, I need to do it in Windows, does that work for me?

**Comment by RcUchiha** [comment]
Hello, after one year.

What should I send in the pull request? The .ts file only?

**Comment by Frechdachs** [comment]
Yes, I'll add language selection in the UI later myself.
